### ISSUE TITLE
timeout 不起作用

### ISSUE THREAD

**Issue by pearloom** [iamyoki/transition-hook#18]
https://codesandbox.io/s/transition-hook-examples-forked-cg426t?file=/src/demos/BasicTransition.jsx:223-331

如官网示例： 我修改timeout，对于组件挂载没有看到有任何影响？

```
 const modalTrans = useTransition(showModal, 30000);
  const buttonTrans = useTransition(!showModal, 30000);
```

**Comment by iamyoki** [comment]
@obligat 你好，实际上是起作用了的，你设置的是30秒后卸载，等30秒后是正常卸载了的。同时注意修改transition duration，通常与hook的timeout保持一致值比较符合预期。

**Comment by pearloom** [comment]
> @obligat 你好，实际上是起作用了的，你设置的是30秒后卸载，等30秒后是正常卸载了的。同时注意修改transition duration，通常与hook的timeout保持一致值比较符合预期。

感谢回答，我有个疑问， clearAnimationFrameTimeout(timer.current);  

```
 useEffect(
    function handleStateChange() {
      clearAnimationFrameTimeout(timer.current);

      // when true - trans from to enter
      // when false - trans enter to leave, unmount after timeout
      if (state) {
        setStage('from');
        setShouldMount(true);
        timer.current = setAnimationFrameTimeout(() => {
          setStage('enter');
        });
      } else {
        setStage('leave');
        timer.current = setAnimationFrameTimeout(() => {
          setShouldMount(false);
        }, timeout);
      }

      return () => {
        clearAnimationFrameTimeout(timer.current);
      };
    },
    [state, timeout]
  );
```

每次运行完都清除了 timer.current  那 `setShouldMount(false);` 怎么还会起作用呢

**Comment by pearloom** [comment]
还有 使用 setAnimationFrameTimeout  有什么好处吗~~  比起 setTimeout ~

**Comment by iamyoki** [comment]
@obligat 前者优先级更高一点，settimeout更新视图会有延迟，而前者永远保持宏任务异步队列中第一帧触发
